# Generated by Django 4.1.6 on 2023-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_body_en_blog_body_ru_blog_body_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default='Test uchun qilingan meta description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
